---
ID: "91ad3f9a-5187-4ea0-a90d-8bf77b9ecba9"
Parent: "3616546f-b468-4345-b5da-2a83be98fdd4"
Template: "3e37c3e2-f56a-4bca-9830-c8ba44740acb"
Path: /sitecore/system/Data Exchange/Data Exchange Tenant for News API/Tenant Settings/Providers/RESTful/Parameters
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{EFE2B784-DF73-459D-BFFB-74F4B0945A3B}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171124T071116Z
