---
ID: "adcea062-9fc4-48f4-8b9b-0d6b1af67daa"
Parent: "012392d9-a3a1-447f-80f8-84114ba0da40"
Template: "012392d9-a3a1-447f-80f8-84114ba0da40"
Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Tenant Settings Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171119T082411Z
