





  

// <autogenerated>
//   This file was generated by T4 code generator.
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </autogenerated>


namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Tenant Settings Folders/RESTful Tenant Settings Application Root
		/// </summary>
        public partial struct RESTfulTenantSettingsApplicationRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{FE96B853-6213-4D05-AFF1-0EBE1FB6E9A5}");
			public const string TemplateName = "RESTful Tenant Settings Application Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Tenant Settings Folders/RESTful Tenant Settings Parameters Root
		/// </summary>
        public partial struct RESTfulTenantSettingsParametersRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{3E37C3E2-F56A-4BCA-9830-C8BA44740ACB}");
			public const string TemplateName = "RESTful Tenant Settings Parameters Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Tenant Settings Folders/RESTful Tenant Settings Resources Root
		/// </summary>
        public partial struct RESTfulTenantSettingsResourcesRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{B6E02B21-9D89-452B-A0D0-124E57BABC65}");
			public const string TemplateName = "RESTful Tenant Settings Resources Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Data Access/Value Accessor Sets/Token Value Accessor Set
		/// </summary>
        public partial struct TokenValueAccessorSet
		{
			public static readonly Guid TemplateId = Guid.Parse("{E87B9305-9D8F-424F-922C-2E3002F46EF4}");
			public const string TemplateName = "Token Value Accessor Set";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Data Access/Value Accessors/Token Value Accessor
		/// </summary>
        public partial struct TokenValueAccessor
		{
			public static readonly Guid TemplateId = Guid.Parse("{33D37828-45EF-4E7E-85BA-775E802CB04F}");
			public const string TemplateName = "Token Value Accessor";
			
            public partial struct FieldIDs
            {
                public static readonly Guid PathExpression = Guid.Parse("{B5421056-DFD5-49F6-AC6B-90A5761E9B57}");
            }

            public partial struct FieldNames
            {
                public const string PathExpression = "Path Expression";
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Data Access/Value Readers/Format Now Value Reader
		/// </summary>
        public partial struct FormatNowValueReader
		{
			public static readonly Guid TemplateId = Guid.Parse("{B73BE55D-8D94-409E-AEFF-6452E7EA98F4}");
			public const string TemplateName = "Format Now Value Reader";
			
            public partial struct FieldIDs
            {
                public static readonly Guid ConvertToUtc = Guid.Parse("{2A586CC4-9C3C-43C3-8A1A-9725AC3AD1AF}");
                public static readonly Guid Format = Guid.Parse("{7460A4C5-551F-4EBC-A224-DC140A3CAB2A}");
            }

            public partial struct FieldNames
            {
                public const string ConvertToUtc = "ConvertToUtc";
                public const string Format = "Format";
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Endpoints/RESTful Endpoint
		/// </summary>
        public partial struct RESTfulEndpoint
		{
			public static readonly Guid TemplateId = Guid.Parse("{BD3F9895-8566-43EE-8014-4A86FC016E2F}");
			public const string TemplateName = "RESTful Endpoint";
			
            public partial struct FieldIDs
            {
                public static readonly Guid Application = Guid.Parse("{4365EEF9-4BF5-4313-9926-D1AAC9CF6B91}");
            }

            public partial struct FieldNames
            {
                public const string Application = "Application";
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Apply Mapping Rules Root
		/// </summary>
        public partial struct RESTfulApplyMappingRulesRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{E18A0E2C-1004-4642-8F7D-89F36BE05DB1}");
			public const string TemplateName = "RESTful Apply Mapping Rules Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Endpoints Root
		/// </summary>
        public partial struct RESTfulEndpointsRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{FC4AF327-8374-473A-AFFD-A2D098B8C3D8}");
			public const string TemplateName = "RESTful Endpoints Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Mappings Applied Action Rules Root
		/// </summary>
        public partial struct RESTfulMappingsAppliedActionRulesRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{869155E0-5F7F-42C2-B347-AB5320E9DE13}");
			public const string TemplateName = "RESTful Mappings Applied Action Rules Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Mappings Applied Actions Root
		/// </summary>
        public partial struct RESTfulMappingsAppliedActionsRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{CE3B2795-C4BE-4CA5-B227-BFC1EF7ECA9C}");
			public const string TemplateName = "RESTful Mappings Applied Actions Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Queue Processors Root
		/// </summary>
        public partial struct RESTfulQueueProcessorsRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{5B141254-C35D-4A49-BCB7-4C64B5B3E954}");
			public const string TemplateName = "RESTful Queue Processors Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Tenant Settings Root
		/// </summary>
        public partial struct RESTfulTenantSettingsRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{012392D9-A3A1-447F-80F8-84114BA0DA40}");
			public const string TemplateName = "RESTful Tenant Settings Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Value Accessor Sets Root
		/// </summary>
        public partial struct RESTfulValueAccessorSetsRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{EC81DE2B-27BF-4B8A-8536-F783A3C559C1}");
			public const string TemplateName = "RESTful Value Accessor Sets Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Value Accessors Root
		/// </summary>
        public partial struct RESTfulValueAccessorsRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{754CB2F1-F12E-49B6-8E74-B9833ED2B964}");
			public const string TemplateName = "RESTful Value Accessors Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Value Readers Root
		/// </summary>
        public partial struct RESTfulValueReadersRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{D8430488-BCD9-4DD3-88AB-6C8C4033C18A}");
			public const string TemplateName = "RESTful Value Readers Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Value Writers Root
		/// </summary>
        public partial struct RESTfulValueWritersRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{B1266101-0CBD-40EF-972F-8BE11713E617}");
			public const string TemplateName = "RESTful Value Writers Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Tenant Settings Folders/RESTful Tenant Settings Headers Root
		/// </summary>
        public partial struct RESTfulTenantSettingsHeadersRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{42EA42DD-E83B-41B3-81DF-31E0B0DAB286}");
			public const string TemplateName = "RESTful Tenant Settings Headers Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Folders/RESTful Tenant Settings Folders/RESTful Tenant Settings Paging Root
		/// </summary>
        public partial struct RESTfulTenantSettingsPagingRoot
		{
			public static readonly Guid TemplateId = Guid.Parse("{4EF69A6E-AF61-4DE3-B061-9D96CD125A81}");
			public const string TemplateName = "RESTful Tenant Settings Paging Root";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Pipeline Steps/Read Resource Data Pipeline Step
		/// </summary>
        public partial struct ReadResourceDataPipelineStep
		{
			public static readonly Guid TemplateId = Guid.Parse("{671F429A-7746-436A-B276-1B4D60A68A45}");
			public const string TemplateName = "Read Resource Data Pipeline Step";
			
            public partial struct FieldIDs
            {
                public static readonly Guid PathExpression = Guid.Parse("{FB647A78-22B6-4233-B0B4-BB434289D7A6}");

				/// Base Template: /sitecore/templates/Data Exchange/Providers/RESTful/Pipeline Steps/Base Templates/_Base Endpoint Pipeline Step
                public static readonly Guid  EndpointFrom = Guid.Parse("{324AC11A-57A3-49C7-814E-9BD75924E8F0}");

				/// Base Template: /sitecore/templates/Data Exchange/Providers/RESTful/Pipeline Steps/Base Templates/_Base Resource Endpoint Pipeline Step
                public static readonly Guid  Resource = Guid.Parse("{42E3A014-5E62-4327-9398-E94972A6DCB0}");
            }

            public partial struct FieldNames
            {
                public const string PathExpression = "Path Expression";

				/// Base Template: /sitecore/templates/Data Exchange/Providers/RESTful/Pipeline Steps/Base Templates/_Base Endpoint Pipeline Step
                public const string EndpointFrom = "EndpointFrom";

				/// Base Template: /sitecore/templates/Data Exchange/Providers/RESTful/Pipeline Steps/Base Templates/_Base Resource Endpoint Pipeline Step
                public const string Resource = "Resource";
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Pipeline Steps/Base Templates/_Base Endpoint Pipeline Step
		/// </summary>
        public partial struct BaseEndpointPipelineStep
		{
			public static readonly Guid TemplateId = Guid.Parse("{87B3FDA3-4683-498F-8EDA-1E44B6D62F27}");
			public const string TemplateName = "_Base Endpoint Pipeline Step";
			
            public partial struct FieldIDs
            {
                public static readonly Guid EndpointFrom = Guid.Parse("{324AC11A-57A3-49C7-814E-9BD75924E8F0}");
            }

            public partial struct FieldNames
            {
                public const string EndpointFrom = "EndpointFrom";
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Pipeline Steps/Base Templates/_Base Resource Endpoint Pipeline Step
		/// </summary>
        public partial struct BaseResourceEndpointPipelineStep
		{
			public static readonly Guid TemplateId = Guid.Parse("{A07D9AD6-D805-4975-BBEF-1601CE5DEA76}");
			public const string TemplateName = "_Base Resource Endpoint Pipeline Step";
			
            public partial struct FieldIDs
            {
                public static readonly Guid Resource = Guid.Parse("{42E3A014-5E62-4327-9398-E94972A6DCB0}");
            }

            public partial struct FieldNames
            {
                public const string Resource = "Resource";
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Settings/HTTP Method
		/// </summary>
        public partial struct HTTPMethod
		{
			public static readonly Guid TemplateId = Guid.Parse("{AB13647C-6E7E-47D9-ADB7-8B39E225821D}");
			public const string TemplateName = "HTTP Method";
			
            public partial struct FieldIDs
            {
            }

            public partial struct FieldNames
            {
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Tenant Settings/Application
		/// </summary>
        public partial struct Application
		{
			public static readonly Guid TemplateId = Guid.Parse("{167C25F4-CEE3-4379-A018-4FAF99E176C7}");
			public const string TemplateName = "Application";
			
            public partial struct FieldIDs
            {
                public static readonly Guid AccessTokenDate = Guid.Parse("{CFCF4613-9A63-4334-9330-4A3C9A3A1ED8}");
                public static readonly Guid AccessToken = Guid.Parse("{A02D2658-8849-43E8-BA6A-6C39BC315538}");
                public static readonly Guid ExpiresIn = Guid.Parse("{DD738E38-D9CD-4235-B5E5-18B2D35FE8D5}");
                public static readonly Guid RefreshToken = Guid.Parse("{D449E6B1-B93A-4D53-B3A6-F919E067B072}");
                public static readonly Guid AuthenticationResource = Guid.Parse("{3C24CA32-C5C1-4165-86B0-3ACB490EC3FE}");
                public static readonly Guid BaseUrl = Guid.Parse("{16CA53E0-8A57-4DB6-8DD3-98C9C148F62A}");
            }

            public partial struct FieldNames
            {
                public const string AccessTokenDate = "Access Token Date";
                public const string AccessToken = "Access Token";
                public const string ExpiresIn = "Expires In";
                public const string RefreshToken = "Refresh Token";
                public const string AuthenticationResource = "Authentication Resource";
                public const string BaseUrl = "Base Url";
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Tenant Settings/Paging
		/// </summary>
        public partial struct Paging
		{
			public static readonly Guid TemplateId = Guid.Parse("{801AB524-9E6D-4D87-A9DA-DAF2501E2D59}");
			public const string TemplateName = "Paging";
			
            public partial struct FieldIDs
            {
                public static readonly Guid CurrentPagePathExpression = Guid.Parse("{E2F7B9FB-45C9-47E9-B823-5309B35E5558}");
                public static readonly Guid FirstPageNumber = Guid.Parse("{BCC6EA40-5AA8-4E53-B537-825F73E74C2B}");
                public static readonly Guid MaximumCount = Guid.Parse("{3C2A7C34-04FA-4AB6-8047-16EBAF4F0912}");
                public static readonly Guid NextTokenPathExpression = Guid.Parse("{54286B8F-12A7-4902-8E83-F59650E9CF45}");
                public static readonly Guid PageSizePathExpression = Guid.Parse("{CF0FCF8C-3B4B-4515-AB49-FF9B59491D6B}");
                public static readonly Guid PageSize = Guid.Parse("{1405E33F-33FD-468D-AF9E-745D98A4C9E6}");
                public static readonly Guid TotalCountPathExpression = Guid.Parse("{64EC9670-FE6A-47BC-967B-886EA5796118}");
            }

            public partial struct FieldNames
            {
                public const string CurrentPagePathExpression = "Current Page Path Expression";
                public const string FirstPageNumber = "First Page Number";
                public const string MaximumCount = "Maximum Count";
                public const string NextTokenPathExpression = "Next Token Path Expression";
                public const string PageSizePathExpression = "Page Size Path Expression";
                public const string PageSize = "Page Size";
                public const string TotalCountPathExpression = "Total Count Path Expression";
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Tenant Settings/Request Header
		/// </summary>
        public partial struct RequestHeader
		{
			public static readonly Guid TemplateId = Guid.Parse("{EDF0DCDD-E7EC-4B51-86D6-5BC7218ABDEB}");
			public const string TemplateName = "Request Header";
			
            public partial struct FieldIDs
            {
                public static readonly Guid HeaderName = Guid.Parse("{835BC979-A99D-4DB5-B9CF-3283C604259B}");
                public static readonly Guid HeaderValue = Guid.Parse("{851F32FD-0886-4EB8-A044-D8928C07AA7D}");
            }

            public partial struct FieldNames
            {
                public const string HeaderName = "Header Name";
                public const string HeaderValue = "Header Value";
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Tenant Settings/Request Parameter
		/// </summary>
        public partial struct RequestParameter
		{
			public static readonly Guid TemplateId = Guid.Parse("{0A115ECE-EBCE-407B-B0ED-9B0D017EBB5C}");
			public const string TemplateName = "Request Parameter";
			
            public partial struct FieldIDs
            {
                public static readonly Guid ParameterToken = Guid.Parse("{CA5DCD55-E1ED-4406-ABBD-1892A2B70AFC}");
                public static readonly Guid ParameterValue = Guid.Parse("{03861819-EBD8-41B9-86CE-D95D2EA7EC6A}");
            }

            public partial struct FieldNames
            {
                public const string ParameterToken = "Parameter Token";
                public const string ParameterValue = "Parameter Value";
            }
		}
	}
}
		
namespace DataExchange.Providers.RESTful
{
	using System;

	public partial struct Templates
    {

		/// <summary>
		/// Path: /sitecore/templates/Data Exchange/Providers/RESTful/Tenant Settings/Resource
		/// </summary>
        public partial struct Resource
		{
			public static readonly Guid TemplateId = Guid.Parse("{CCD271B0-85F4-461A-A87A-F6B2C6C992BC}");
			public const string TemplateName = "Resource";
			
            public partial struct FieldIDs
            {
                public static readonly Guid Headers = Guid.Parse("{1560BFA0-AA7E-44D8-8424-0E317AA9CA36}");
                public static readonly Guid Method = Guid.Parse("{676CB7D4-CCD9-4BB6-9984-C75E038C550E}");
                public static readonly Guid Paging = Guid.Parse("{634E135D-DA79-489C-8C42-5115F6EDBCD7}");
                public static readonly Guid Parameters = Guid.Parse("{5E387F3D-719F-4B04-AB75-99640EC5A972}");
                public static readonly Guid Url = Guid.Parse("{DA7CE9A8-BFAB-43A8-A88C-4A780C79EDDF}");
            }

            public partial struct FieldNames
            {
                public const string Headers = "Headers";
                public const string Method = "Method";
                public const string Paging = "Paging";
                public const string Parameters = "Parameters";
                public const string Url = "Url";
            }
		}
	}
}
		

